name: Auto pack extensions and Publish release
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 4 * * *" # Runs every day at 00:00

jobs:
  pack-and-release:
    runs-on: ubuntu-latest
    outputs:
      otd_ver: ${{ steps.latest-ver.outputs.otd_ver }}
      btd_ver: ${{ steps.latest-ver.outputs.btd_ver }}
      tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Get latest version
        id: latest-ver
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          echo "otd_ver=$(gh release list -R "dimdenGD/OldTweetDeck" | head -n1 | awk -F' ' '{print $2}')" >> $GITHUB_OUTPUT
          echo "btd_ver=$(gh release list -R "dimdenGD/BetterTweetDeck" | head -n1 | awk -F' ' '{print $4}' | sed -e 's/v//g')" >> $GITHUB_OUTPUT

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: "minor"

      - name: Pack extensions
        run: |
          curl -LJO https://github.com/dimdenGD/BetterTweetDeck/releases/download/v${{ steps.latest-ver.outputs.btd_ver }}/Chrome.zip
          curl -LJO https://github.com/dimdenGD/OldTweetDeck/releases/download/v${{ steps.latest-ver.outputs.otd_ver }}/OldTweetDeckChrome.zip

          unzip Chrome.zip -d BetterTweetDeck_${{ steps.latest-ver.outputs.btd_ver }}_Chromium
          unzip OldTweetDeckChrome.zip -d OldTweetDeck_${{ steps.latest-ver.outputs.otd_ver }}_Chromium

          pushd BetterTweetDeck_${{ steps.latest-ver.outputs.btd_ver }}_Chromium
          mv manifest.json manifest_tmp.json
          cat < manifest_tmp.json | jq '.+ {"update_url": "https://raw.githubusercontent.com/misumisumi/Chromium-Extensions-auto-packer/main/BetterTweetDeckOTD/updates.xml"}' > manifest.json
          popd

          pushd OldTweetDeck_${{ steps.latest-ver.outputs.otd_ver }}_Chromium
          mv manifest.json manifest_tmp.json
          cat < manifest_tmp.json | jq '.+ {"update_url": "https://raw.githubusercontent.com/misumisumi/Chromium-Extensions-auto-packer/main/OldTweetDeck/updates.xml"}' > manifest.json
          popd

          cat ${{ secrets.BETTERTWEETDECKPEM }} > BTD.pem
          cat ${{ secrets.OLDTWEETDECKPEM }} > OTD.pem

          chromium --pack-extension=BetterTweetDeck_${{ steps.latest-ver.outputs.btd_ver }}_Chromium --pack-extension-key=BTD.pem
          chromium --pack-extension=OldTweetDeck_${{ steps.latest-ver.outputs.otd_ver }}_Chromium --pack-extension-key=OTD.pem

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: "OldTweetDeck_${{ needs.update-xml.outputs.otd_ver }}_Chromium.crx,BetterTweetDeck_${{ needs.update-xml.outputs.btd_ver }}_Chromium.crx"

  update-xml:
    runs-on: ubuntu-latest
    needs: pack-and-release
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Update updates.xml
        run: |
          REPO_OTD=dimdenGD/OldTweetDeck
          REPO_BTD=dimdenGD/BetterTweetDeck

          cat <<EOF >OldTweetDeck/updates.xml
          <?xml version='1.0' encoding='UTF-8'?>
          <gupdate xmlns='http://www.google.com/update2/response' protocol='2.0'>
            <app appid='ilpagdghakcfnlaanggbgjbmdflagajb'>
              <updatecheck codebase='https://github.com/misumisumi/Chromium-Extensions-auto-packer/releases/download/${{ needs.pack-and-release.outputs.tag }}/OldTweetDeck_${{ needs.pack-and-release.outputs.otd_ver }}_Chromium.crx' version='${{ needs.pack-and-release.outputs.otd_ver }}' status='ok' />
            </app>
          </gupdate>
          EOF

          cat <<EOF >BetterTweetDeckOTD/updates.xml
          <?xml version='1.0' encoding='UTF-8'?>
          <gupdate xmlns='http://www.google.com/update2/response' protocol='2.0'>
            <app appid='mbkealjjbgdefaeolfjpmohgkbejfnli'>
              <updatecheck codebase='https://github.com/misumisumi/Chromium-Extensions-auto-packer/releases/download/${{ needs.pack-and-release.outputs.tag }}/BetterTweetDeck_${{ needs.pack-and-release.outputs.btd_ver }}_Chromium.crx' version='${{ needs.pack-and-release.outputs.btd_ver }}' status='ok' />
            </app>
          </gupdate>
          EOF

      - name: Update README.md
        run: |
          cat <<EOF >README.md
          # Chromium extensions auto packer

          Automatic generation of 'crx file' and 'updates.xml' of chromium extensions.

          Automatically keep up with the latest version.

          ## Available Extensions

          - [OldTweetDeck](https://github.com/dimdenGD/OldTweetDeck)-${{ steps.latest-ver.outputs.btd_ver }}
          - [BetterTweetDeck (OldTweetDeck-compatible)](https://github.com/dimdenGD/BetterTweetDeck/)-${{ steps.latest-ver.outputs.btd_ver }}
          EOF

      - name: Commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "*/updates.xml README.md"