name: Auto pack extensions and Publish release
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  pack-and-release:
    runs-on: ubuntu-latest
    outputs:
      otd_ver: ${{ steps.latest-ver.outputs.otd_ver }}
      btd_ver: ${{ steps.latest-ver.outputs.btd_ver }}
      tag: ${{ steps.tag_version.outputs.new_tag }}
      need_update: ${{ steps.latest-ver.outputs.btd_ver != steps.latest-ver.outputs.now_btd_ver || steps.latest-ver.outputs.otd_ver != steps.latest-ver.outputs.now_otd_ver }}
    steps:
      - uses: actions/checkout@v4

      - name: Get latest version
        id: latest-ver
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          echo "btd_ver=$(gh release list -R "dimdenGD/BetterTweetDeck"  --json tagName --jq ".[0].tagName" | sed -e 's/v//g')" >> $GITHUB_OUTPUT
          echo "otd_ver=$(gh release list -R "dimdenGD/OldTweetDeck" --json tagName --jq ".[0].tagName" | sed -e 's/v//g')" >> $GITHUB_OUTPUT
          echo "now_btd_ver=$(gh release view --json 'assets' -q '.[].[] | .name' | grep BetterTweetDeck | awk -F'_' '{print $2}')" >> $GITHUB_OUTPUT
          echo "now_otd_ver=$(gh release view --json 'assets' -q '.[].[] | .name' | grep OldTweetDeck | awk -F'_' '{print $2}')" >> $GITHUB_OUTPUT

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        if: steps.latest-ver.outputs.btd_ver != steps.latest-ver.outputs.now_btd_ver || steps.latest-ver.outputs.otd_ver != steps.latest-ver.outputs.now_otd_ver
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: "minor"

      - name: Save the sercret file
        if: steps.latest-ver.outputs.btd_ver != steps.latest-ver.outputs.now_btd_ver || steps.latest-ver.outputs.otd_ver != steps.latest-ver.outputs.now_otd_ver
        run: |
          echo '${BTD_SECRET}' > temp_btd.pem
          echo '${OTD_SECRET}' > temp_otd.pem
          envsubst < temp_btd.pem > BTD.pem
          envsubst < temp_otd.pem > OTD.pem
        env:
          BTD_SECRET: ${{ secrets.BETTERTWEETDECKPEM }}
          OTD_SECRET: ${{ secrets.OLDTWEETDECKPEM }}

      - name: Pack extensions
        if: steps.latest-ver.outputs.btd_ver != steps.latest-ver.outputs.now_btd_ver || steps.latest-ver.outputs.otd_ver != steps.latest-ver.outputs.now_otd_ver
        run: |
          curl -LJO https://github.com/dimdenGD/BetterTweetDeck/releases/download/v${{ steps.latest-ver.outputs.btd_ver }}/Chrome.zip
          curl -LJO https://github.com/dimdenGD/OldTweetDeck/releases/download/v${{ steps.latest-ver.outputs.otd_ver }}/OldTweetDeckChrome.zip

          unzip Chrome.zip -d BetterTweetDeck_${{ steps.latest-ver.outputs.btd_ver }}_Chromium
          unzip OldTweetDeckChrome.zip -d OldTweetDeck_${{ steps.latest-ver.outputs.otd_ver }}_Chromium

          pushd BetterTweetDeck_${{ steps.latest-ver.outputs.btd_ver }}_Chromium
          mv manifest.json manifest_tmp.json
          cat manifest_tmp.json | jq '.+ {"update_url": "https://raw.githubusercontent.com/misumisumi/Chromium-Extensions-auto-packer/main/BetterTweetDeckOTD/updates.xml"}' > manifest.json
          popd

          pushd OldTweetDeck_${{ steps.latest-ver.outputs.otd_ver }}_Chromium
          mv manifest.json manifest_tmp.json
          cat manifest_tmp.json | jq '.+ {"update_url": "https://raw.githubusercontent.com/misumisumi/Chromium-Extensions-auto-packer/main/OldTweetDeck/updates.xml"}' > manifest.json
          popd

          google-chrome --pack-extension=BetterTweetDeck_${{ steps.latest-ver.outputs.btd_ver }}_Chromium --pack-extension-key=BTD.pem
          google-chrome --pack-extension=OldTweetDeck_${{ steps.latest-ver.outputs.otd_ver }}_Chromium --pack-extension-key=OTD.pem

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        if: steps.latest-ver.outputs.btd_ver != steps.latest-ver.outputs.now_btd_ver || steps.latest-ver.outputs.otd_ver != steps.latest-ver.outputs.now_otd_ver
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: "OldTweetDeck_${{ steps.latest-ver.outputs.otd_ver }}_Chromium.crx,BetterTweetDeck_${{ steps.latest-ver.outputs.btd_ver }}_Chromium.crx"

      - name: Check env
        run: |
          echo need_update=${{ steps.latest-ver.outputs.btd_ver != steps.latest-ver.outputs.now_btd_ver || steps.latest-ver.outputs.otd_ver != steps.latest-ver.outputs.now_otd_ver }}

  update-xml:
    runs-on: ubuntu-latest
    needs: pack-and-release
    if: needs.pack-and-release.outputs.need_update == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Update updates.xml
        run: |
          REPO_OTD=dimdenGD/OldTweetDeck
          REPO_BTD=dimdenGD/BetterTweetDeck

          cat <<EOF >BetterTweetDeckOTD/updates.xml
          <?xml version='1.0' encoding='UTF-8'?>
          <gupdate xmlns='http://www.google.com/update2/response' protocol='2.0'>
            <app appid='ajdlpmoffekghhblfajmiacgbdknmbpa'>
              <updatecheck codebase='https://github.com/misumisumi/Chromium-Extensions-auto-packer/releases/download/${{ needs.pack-and-release.outputs.tag }}/BetterTweetDeck_${{ needs.pack-and-release.outputs.btd_ver }}_Chromium.crx' version='${{ needs.pack-and-release.outputs.btd_ver }}' status='ok' />
            </app>
          </gupdate>
          EOF

          cat <<EOF >OldTweetDeck/updates.xml
          <?xml version='1.0' encoding='UTF-8'?>
          <gupdate xmlns='http://www.google.com/update2/response' protocol='2.0'>
            <app appid='bjcdldglejahkljjcjhpdclapfpiphhf'>
              <updatecheck codebase='https://github.com/misumisumi/Chromium-Extensions-auto-packer/releases/download/${{ needs.pack-and-release.outputs.tag }}/OldTweetDeck_${{ needs.pack-and-release.outputs.otd_ver }}_Chromium.crx' version='${{ needs.pack-and-release.outputs.otd_ver }}' status='ok' />
            </app>
          </gupdate>
          EOF

      - name: Update README.md
        run: |
          cat <<EOF >README.md
          # Chromium extensions auto packer

          Automatic generation of 'crx file' and 'updates.xml' of chromium extensions.

          Automatically keep up with the latest version.

          ## Available Extensions

          - [BetterTweetDeck (OldTweetDeck-compatible)](https://github.com/dimdenGD/BetterTweetDeck/)-${{ needs.pack-and-release.outputs.btd_ver }}
          - [OldTweetDeck](https://github.com/dimdenGD/OldTweetDeck)-${{ needs.pack-and-release.outputs.otd_ver }}
          EOF

      - name: Commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "*/updates.xml README.md"
